- src/Tymon/JWTAuth/JWTAuth.php
`Illuminate\Auth\Guard::onceUsingId() ` not always return boolean，when the user id in the token does not exist or has been deleted will cause an exception:
https://github.com/laravel/framework/blob/4.2/src/Illuminate/Auth/Guard.php#L482
if `$this->provider->retrieveById($id)` return null;
then https://github.com/laravel/framework/blob/4.2/src/Illuminate/Auth/Guard.php#L682 Will throw an exception：
```shell
Argument 1 passed to Illuminate\Auth\Guard::setUser() must implement interface Illuminate\Auth\UserInterface, null given, called in xxxxxxx/vendor/laravel/framework/src/Illuminate/Auth/Guard.php on line 482 and defined
```
> onceUsingId() not always return boolean

- src/Providers/User/EloquentUserAdapter.php
Hey,
this is my first pull request on GitHub, so maybe I am doing it wrong. :-)
I like your package and I would use it in one of my projects, but I noticed that it doesn't work as expected. But if you return the user in the EloquentUserAdapter like so, everything works fine for me. So I can do:
$token = JWTAuth::getToken();
$user = JWTAuth::toUser($token);
And have accesss to the User. Great!
Looking forward to the updates and thank you for the package!
Regards,
Thomas
PS: Would it be possible to just have a method JWTAuth::getUser() which will return the user without having to get the token first?
> We have to return the user

- src/JWTAuth.php
Right now method chaining doesn't work, e.g. you can't do the following:
```
$user = JWTAuth::parseToken()->toUser();
// will throw TokenInvalidException('Wrong number of segments');
```
`JWTAuth::parseToken()` will set the token property in JWTAuth class to the token in the header. If we chain `->toUser()` the requireToken() method will not throw an exception as there is a token set to the object, but in the end we just pass in the $token (which is false) to setToken(). Therefore, throwing an TokenInvalidException('Wrong number of segments').
The change should enable that we can chain these methods.
> Fix requireToken()

- src/JWTManager.php
- tests/JWTManagerTest.php
I had an issue where I would always get a expired token error when trying to refresh a token that is expired, but still within the refresh_ttl.
I found that the token was being validated before the refreshFlow was enabled. This pull request adds the ability to start the refresh flow before validating.
Another user encountered the same problem and created issue #101
> Fix issue causing auth refresh to fail

- src/Validators/PayloadValidator.php
The TokenExpired exception was being created with a 400 status when it should be 401.
> Fixed TokenExpired response

- composer.json
- src/Providers/JWT/NamshiAdapter.php
This is a follow up to a patch I did on namshi/jose. The encoding for the token signature was slightly wrong, so tokens weren't language interoperable.
> bumped namshi/jose to 5.0: tokens are now interoperable

- src/Factory.php
- src/JWTAuth.php
* In `JWTAuth::getClaimsArray`, the subject claim retrieved from `$user->getJWTIdentified()` was taking the highest priority. IMO, if someone decides to set the subject as a custom claim, their decision should be respected. (It's a weird case, but I think it's preferable to having an inconsistency in the general rule of custom claims trumping default claims.)
* In `Factory::buildClaims`, two lefts were making a right: The removed `array_diff_key` did nothing (the custom claims are `claimName => value` while the default claims are `[auto-index] => claimName`, so they would never match). But presumably the code that would've handled the removed cases got factored out somewhere along the way, as all that remains is the code adding missing defaults. I figured it was easiest to leave the flow …
> Two minor fixes for applying default claims

- src/Providers/Storage/Illuminate.php
- tests/Providers/Storage/IlluminateTest.php
Made a mistake there since we actually looking for a class that can
resolved to `cache.store` alias. Laravel can resolve with
`Illuminate\Cache\Repository` or `Illuminate\Contracts\Cache\Repository`
while Lumen can only resolve with
`Illuminate\Contracts\Cache\Repository`
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Application.php#L1035
https://github.com/laravel/lumen-framework/blob/5.1/src/Application.php#L1659
Signed-off-by: crynobone <crynobone@gmail.com>
> Fixes typehint based on comment by @mod3st

- src/Validators/PayloadValidator.php
Found and fixed an issue causing the validator not to honour the "required_claims" configuration.
> Use array_diff to check presence of required claims

- src/JWTAuth.php
In some situations, for example in unit testing, we need to clear currently saved token.
> Added remove token method

- src/Http/TokenParser.php
- tests/Http/TokenParserTest.php
… because parsing headers and GET parameters is not enough :smirk:
> TokenParser should take into account route parameters

- .travis.yml
- composer.json
* Add support for Laravel 5.1 and Laravel 5.2
* Update travis-ci to include test on both setup.
~~There one failing on laravel 5.1 test at the moment. I not sure how that would relate with the changes.~~
> Add support for Laravel 5.2

- composer.json
Composer now recommends to use `||` instead of just one `|`.
> Switch to new recommended composer syntax.

- src/Providers/Storage/Illuminate.php
- tests/Providers/Storage/IlluminateTest.php
Existing checks for whether a cache supported `tags()` were quietly failing because it was handled by magical `__call` in L5.1.27 and lower. Instead of a raw method exists, this PR captures exceptions on `tags` (to handle L5.1.28) and also examine the store if a `getStore` method is available (for older releases). This fixes #367.
I also uncovered why this hadn't been caught by the tests: Using the "Demeter chain" syntax wasn't actually checking whether `tags()` was getting called, because Mockery shortcuts those checks when it knows what the output would be and only verifies the final method in the chain. Instead we separate the chain method expectations, as well as enforcing they are actually called (with `once()`) and duplicating them to have separate tests for the tagged and untagged …
> Provide support for tagged caches and squash L5.1.28 breakage

- src/Http/LumenRouteParams.php
- src/Http/Parser.php
- src/Http/RouteParams.php
- tests/Http/ParserTest.php
Added `is_callable` check for `parameter` method that was throwing fatal errors when trying to parse Lumen requests and requests that had never been dispatched, along with appropriate tests.
Also allow parsing chain to be retrieved using `JWTAuth::parser()->getChain()`, and provide a small experimental class to support unstable Lumen route params.
Addresses components of #384 & #376, and fixes #361.
> Make route parameter parsing safer

- src/Providers/Auth/IlluminateAuthAdapter.php
- tests/Providers/Auth/IlluminateAuthAdapterTest.php
I'm concerned that this try-catch that got removed on develop (6f7ccb7d0c28da416831fcaac27e0a4e5d242bee) is impeding debugging issues people are having on master as well, because Auth exceptions show up through the middleware there as `user_not_found`. This could be the root cause of #393 & #397 for example...
> Bring auth-exception-bubbling fix to 0.5

- src/Middleware/BaseMiddleware.php
- tests/Middleware/GetUserFromTokenTest.php
This fixes errors with class mismatch of mocked components as described in #402. There it was triggered by `$laravelTestCase->withoutEvents()` but I think there are other methods that might've had problems.
Also addresses the extremely unlikely but still valid issue of compatibility for anyone using a non-stock implementation of `Events\Dispatcher` or `Routing\ResponseFactory`. 
(Unfortunately building a test specifically for this would require including all of Laravel, because, as far as I can tell, there isn't a standalone repo that contains `Illuminate\Foundation\Testing`.)
Thanks to @kontrollanten for the diff.
> Use contracts for dispatch and response in base middleware

- src/JWTGuard.php
Current implementation is throwing a `BadRequestHttpException`.
Although I agree this is a fault on the client side that is not including the required access token when submitting the request, having `JWTGuard` throwing a package specific exception type makes it easier to intercept the exception and customize its message as needed.
Also that keeps the implementation consistent with the [examples given on the wiki](https://github.com/tymondesigns/jwt-auth/wiki/Authentication#retreiving-the-authenticated-user-from-a-token).
> Throws `JWTException` type on required token absent

- src/Exceptions/InvalidClaimException.php
- src/Exceptions/PayloadException.php
- src/Exceptions/TokenBlacklistedException.php
- src/Exceptions/TokenExpiredException.php
- src/Exceptions/TokenInvalidException.php
It's more a convention than something else, meaning that the class is left empty on purpose
> Add double slashes to empty exceptions

- src/Commands/JWTGenerateSecretCommand.php
Since L5.1, we can use command signatures which are much more readable.
> Use a command signature

- src/Http/AuthHeaders.php
> Fix docblock

- .travis.yml
Failure should not be allowed anymore for PHP 7.
> Disallow failure for php 7

- src/Blacklist.php
- src/Providers/JWTAuthServiceProvider.php
- tests/BlacklistTest.php
- tests/PayloadFactoryTest.php
- tests/PayloadTest.php
- tests/Providers/JWT/NamshiAdapterTest.php
- tests/Validators/PayloadValidatorTest.php
Remake of the fix way back in #218 that I neglected to realize only ever made it to develop and not master. :dizzy_face:
Now expired-but-refreshable tokens can be blacklisted, which should fix a few refreshes people are seeing that should not succeed! Fixes #419, potentially related to some confusing situations like #378.
> Allow expired-but-refreshable tokens to be blacklisted (again)

- src/Validators/PayloadValidator.php
Remains consistant with the syntax used for `\Tymon\JWTAuth\Validators\PayloadValidator::validateTimestamps`
> Consistant comparison

- .styleci.yml
They should be actual sentences so need to end in a fullstop. You should be able to merge the StyleCI changes easily yourself after this PR.
> Fix phpdoc short descriptions

- src/Commands/JWTGenerateSecretCommand.php
I apparently felt the need to live on the bleeding edge and immediately realized the jwt:secret command was broken. I would get the following exception:
`[Symfony\Component\Console\Exception\RuntimeException]  
Not enough arguments (missing: "show").`
It looks like the signature requires -- or - for commands. Changed the command to be --show and added an alias to -s. Also removed the word 'simply' to fall in line with other artisan commands.
> Fixing jwt:secret command

- composer.json
- tests/BlacklistTest.php
- tests/FactoryTest.php
- tests/Http/ParserTest.php
- tests/JWTAuthTest.php
- tests/JWTGuardTest.php
- tests/ManagerTest.php
- tests/Middleware/AuthenticateTest.php
- tests/Middleware/CheckTest.php
- tests/Middleware/RefreshTokenTest.php
- tests/PayloadTest.php
- tests/Providers/Auth/IlluminateTest.php
- tests/Providers/Auth/OctoberTest.php
- tests/Providers/Auth/SentinelTest.php
- tests/Providers/JWT/NamshiTest.php
- tests/Providers/Storage/IlluminateTest.php
Use `::class` notation.
---
Also add missing `"illuminate/routing": "5.1.* || 5.2.*"` in `require-dev`
> Use ::class notation

- src/Middleware/RefreshToken.php
No need to generate `$response` if it's not returned
> No need to generate $response if it's not returned

- src/Validators/PayloadValidator.php
Only one class comment was set in all files for `\Tymon\JWTAuth\Validators\PayloadValidator`.
I suppose this is not on purpose.
> Remove class comment

- src/Blacklist.php
- src/Factory.php
- tests/AbstractTestCase.php
Directly call `\DateTime::getTimestamp`, no need to call `\Carbon\Carbon::__get`
> Directly call \DateTime::getTimestamp

- src/Http/Middleware/Authenticate.php
- src/Http/Middleware/BaseMiddleware.php
- src/Http/Middleware/Check.php
- src/Http/Middleware/RefreshToken.php
- src/Providers/LaravelServiceProvider.php
- tests/Middleware/AuthenticateTest.php
- tests/Middleware/CheckTest.php
- tests/Middleware/RefreshTokenTest.php
Respect Laravel app architecture and move \Middleware to \Http\Middleware
> Move \Middleware to \Http\Middleware

- src/Providers/LumenServiceProvider.php
> Fix , => typo in LumenServiceProvider

- config/config.php
- src/Validators/PayloadValidator.php
- tests/Validators/PayloadValidatorTest.php
Similar to how never expiring tokens is currently supported, adds support for infinite refresh TTL time. 
Just like how you can set `JWT_TTL=null`, adds support to set `JWT_REFRESH_TTL=null`.
Opposed to using never expiring tokens, a mobile app developer may want the additional security of having tokens expire after some time (say, in case it is compromised in transit somehow, at least it may expire before it could be used maliciously), but allows the mobile app to refresh the token with the server at any time after it expires.
> Add Ability To Set Infinite Refresh TTL

- tests/Http/ParserTest.php
Add tests for `\Tymon\JWTAuth\Http\Parser\QueryString::setKey`
> Add tests for \Tymon\JWTAuth\Http\Parser\QueryString::setKey

- src/Http/Parser/LumenRouteParams.php
Directly return the value (if not `null`)
> LumenRouteParams : Directly return the value

- tests/FactoryTest.php
Test `\Tymon\JWTAuth\Support\CustomClaims::customClaims`, not its alias.
---
Tests failing for another reason
> Tests \Tymon\JWTAuth\Support\CustomClaims::customClaims

- composer.json
You're building the 1.0 version on the develop branch now, right? Or are you still planning to release 0.6?
In that case, change the branch-alias to 1.0, so people can require `1.x@dev` and get the latest dev version (instead of the alpha)
> Update branch-alias to 1.0-dev

- src/Blacklist.php
- src/Claims/Claim.php
- src/Claims/Custom.php
- src/Factory.php
- src/Http/Middleware/BaseMiddleware.php
- src/Http/Parser/Parser.php
- src/JWT.php
- src/JWTAuth.php
- src/JWTGuard.php
- src/Manager.php
- src/Payload.php
- src/Providers/Auth/Illuminate.php
- src/Providers/Auth/October.php
- src/Providers/Auth/Sentinel.php
- src/Providers/JWT/Namshi.php
- src/Providers/JWT/Provider.php
- src/Providers/Storage/Illuminate.php
- src/Token.php
Return void was sometimes set for `__construct`, sometimes not.
This PR sets it everywhere to respect Laravel coding style
---
**Note:** in some cases there is an empty line before `@return`, in some other not.
StyleCI does not find anything wrong - but IMO, it think it should
> Add return void docblock

- .travis.yml
Also tests with PHP > `5.5.9`
---
https://travis-ci.org/tymondesigns/jwt-auth/jobs/126997619 and https://travis-ci.org/tymondesigns/jwt-auth/jobs/126997620 pass with PHP `5.5.21`
> Also tests with PHP > 5.5.9

- src/PayloadFactory.php
- src/Validators/PayloadValidator.php
- tests/PayloadFactoryTest.php
- tests/Validators/PayloadValidatorTest.php
Issue in 0.5 that I mentioned in #719.
- Simplify `PayloadFactory` addition of custom claims and prevent issue with numerically-keyed claims.
- Fix `PayloadValidator` required claims check, which was only verifying that there were at least as many claims as requireds and not comparing keys.
- Create tests for both scenarios.
> Fix claims array comparisons

- src/PayloadFactory.php
- tests/PayloadFactoryTest.php
The default `jti` would stumble on unstringable `sub` values, which were occasionally happening for some users.
Addresses #719 and #351 and another one I can't find. Or rather it fixes a _symptom_ of those issues. I don't think anyone has identified why they had a non-standard subject value (and whether it was their app or some edge case in the library), but there isn't a good reason `jti` should choke on that scenario.
> Bailout to json_encode when building jti claims

- src/Console/JWTGenerateSecretCommand.php
Uses correct line endings on the target platform.
> Replace CRLF with PHP_EOL

- src/Exceptions/UserNotDefinedException.php
- src/JWTGuard.php
- tests/JWTGuardTest.php
Before the method used to return `null` which was a cause of frustration every time someone wanted to just do `Auth::user()->email` (for example). Instead, we had to perform checks every time we call that function. With the exception thrown instead, we can ensure that nothing unexpected happens and keep the code clean.
Note: I wasn't sure how to name the exception the best way, so change it to whatever you think is better.
> Made the JWTGuard->user() method throw an exception in case of failure

- src/Console/JWTGenerateSecretCommand.php
As it stands you cannot generally call `JWTGenerateSecretCommand` from code because it will hit a user confirmation dialog when replacing an existing key, and as far as I can tell, there isn't an easy way to respond to artisan command dialogs from within the application. Providing a `--force` option allows us to skip this dialog for in-app command calls (it can also simplify build scripts that might be regenerating keys, so they no longer need to pipe in a "y").
> Give secret generation command a `--force` option

- src/Providers/JWT/Provider.php
No need to call `\Tymon\JWTAuth\Providers\JWT\Provider::getKeys`
> Directly access \Tymon\JWTAuth\Providers\JWT\Provider::$keys

- src/Console/JWTGenerateSecretCommand.php
- src/Factory.php
Use `\Illuminate\Support\Str::random` - `\Illuminate\Support\Str::quickRandom` is deprecated since `5.3`
> Use \Illuminate\Support\Str::random.

- src/Blacklist.php
If the key in `has` method isn't found, `Utils::isFuture` will send a NULL value to Carbon who will throw an exception. Can happen if storage doesn't find a blacklist key.
> Blacklist sends NULL to Carbon

- src/Providers/JWTAuthServiceProvider.php
Laravel 5.4 removed the `share()` method as well the option to pass an array of parameters to `make()`.
This pull request fixes both of this in the JWTAuthServiceProvider
> Add Laravel 5.4 compatibility

- src/Providers/LaravelServiceProvider.php
In Laravel 5.4 there is now a aliasMiddleware method that does what the middleware function did before.  I do an if statement check so the middleware will be compatible with previous versions of Laravel 5 as well.  This is a fix for issue #972
> fix LaravelServiceProvider for L 5.4

- src/Http/Middleware/BaseMiddleware.php
- tests/Middleware/AuthenticateTest.php
Currently, in the 1.0 branch, the auth middleware will not throw an exception if the JWT token is valid, but the user in the `sub` claim no longer exists. This functionality existed in pre-1.0 versions.
In previous versions, this threw a 404, however I believe a 401 is more appropriate.
It may also be worth invalidating the token in such cases, but I didn't add it into this PR.
> Throw if user no longer exists in authentication middleware

- src/Manager.php
After the fix for issue #1060 the refresh middleware stopped working because it would check the blacklist and then fail because the token is already invalidated.  If you move the invalidation til after the "buildRefreshClaims" method then you don't have this problem.
> invalidate the old token AFTER building the claim

- src/Http/Middleware/BaseMiddleware.php
- tests/Middleware/AuthenticateAndRenewTest.php
- tests/Middleware/AuthenticateTest.php
- tests/Middleware/RefreshTokenTest.php
This was discussed in https://github.com/tymondesigns/jwt-auth/issues/1024
`400` represents a mal-formed request.
`401` is specifically for use when authentication is required or has not yet been provided.
> Correct status code for missing auth tokens

- src/Providers/JWTAuthServiceProvider.php
This fixes the error `Call to undefined method Illuminate\Foundation\Application::share()` when publishing it on the installation, caused by removal of the api call on laravel 5.4.
https://github.com/tymondesigns/jwt-auth/issues/1144
> Laravel 5.4 fix for API depreciation
