tymondesigns/jwt-auth

src/Providers/User/EloquentUserAdapter.php

JWTAuth::toUser($token) was not returning a User

Fix user query not being returned in getBy

---

src/JWTAuth.php

@tymondesigns requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/tymondesigns/jwt-auth/

Scrutinizer Auto-Fixes

---

src/Blacklist.php
src/Providers/LumenServiceProvider.php
tests/BlacklistTest.php

Squashed version of #218
(Keep me away from the command line, and things would be easier)

Fix issues with blacklisting expired tokens and refreshing blacklisted tokens (squashed)

---

src/Providers/Auth/Illuminate.php
src/Providers/Storage/Illuminate.php
tests/Providers/Auth/IlluminateTest.php
tests/Providers/Storage/IlluminateTest.php

Alternative to #219 and fixes #179 
Signed-off-by: crynobone <crynobone@gmail.com>

Use contracts instead of concrete implementation (managers) that can't be resolved via IoC.

---

src/Providers/LumenServiceProvider.php

Signed-off-by: crynobone <crynobone@gmail.com>

Allow to use custom config path for jwt when using Lumen.

---

src/Blacklist.php
src/Http/AuthHeaders.php
src/Http/Parser.php
src/Http/QueryString.php
src/JWTGuard.php
src/Validators/PayloadValidator.php

Fix some docblocks

---

src/Factory.php
tests/BlacklistTest.php
tests/Claims/ClaimTest.php
tests/Claims/FactoryTest.php
tests/FactoryTest.php
tests/Middleware/AuthenticateTest.php
tests/Middleware/RefreshTokenTest.php
tests/PayloadTest.php
tests/Providers/JWT/NamshiTest.php
tests/Providers/JWT/ProviderTest.php
tests/Stubs/UserStub.php
tests/Validators/PayloadValidatorTest.php

Remove unused use

---

.php_cs

Also check /tests files

---

.php_cs
.styleci.yml
src/Blacklist.php
src/Claims/Claim.php
src/Claims/Expiration.php
src/Claims/Factory.php
src/Claims/IssuedAt.php
src/Claims/NotBefore.php
src/Contracts/Claim.php
src/Contracts/Providers/Storage.php
src/Contracts/Validator.php
src/Http/Parser.php
src/JWT.php
src/JWTGuard.php
src/Manager.php
src/Payload.php
src/Providers/Auth/Illuminate.php
src/Providers/Auth/Sentinel.php
src/Providers/Storage/Illuminate.php
src/Validators/PayloadValidator.php
src/Validators/TokenValidator.php
src/Validators/Validator.php

Use scalar notation

---

src/Middleware/Check.php
src/Providers/Storage/Illuminate.php

Add some missing imports

---

.php_cs
.styleci.yml
src/Http/LumenRouteParams.php
src/Http/Parser.php
src/Http/RouteParams.php
src/Providers/Storage/Illuminate.php
tests/Http/ParserTest.php

Only found some whitespacy lines

Add more fixers to comply to the code style

---

tests/BlacklistTest.php
tests/Claims/ClaimTest.php
tests/FactoryTest.php
tests/Http/ParserTest.php
tests/JWTAuthTest.php
tests/Middleware/RefreshTokenTest.php
tests/PayloadTest.php
tests/Providers/Auth/IlluminateTest.php
tests/Providers/Auth/SentinelTest.php
tests/Providers/JWT/NamshiTest.php
tests/Providers/JWT/ProviderTest.php
tests/Providers/Storage/IlluminateTest.php

Use stricter / proper assertions

Use stricter / proper assertions

---

src/Blacklist.php
src/Claims/Claim.php
src/Contracts/Claim.php
src/Factory.php
src/Http/Parser.php
src/Http/QueryString.php
src/Http/RouteParams.php
src/JWT.php
src/JWTGuard.php
src/Manager.php
src/Providers/JWT/Provider.php
src/Support/CustomClaims.php
src/Support/RefreshFlow.php
src/Validators/PayloadValidator.php

Allows `return $this` have a `@return $this` but these ones.
This PR fix this inconstancy.

Fix some return docblocks

---

src/Exceptions/JWTException.php
src/JWT.php
src/Middleware/Authenticate.php
src/Middleware/Check.php
src/Middleware/RefreshToken.php
src/Payload.php

More imports

---

.scrutinizer.yml

All this checks are already handled by StyleCi

Remove styleci parts

---

.gitattributes

No need to export `.editorconfig`

No need to export .editorconfig

---

tests/BlacklistTest.php
tests/Claims/ClaimTest.php
tests/Claims/FactoryTest.php
tests/FactoryTest.php
tests/JWTAuthTest.php
tests/ManagerTest.php
tests/Middleware/AuthenticateTest.php
tests/Middleware/CheckTest.php
tests/Middleware/RefreshTokenTest.php
tests/PayloadTest.php
tests/Providers/Auth/IlluminateTest.php
tests/Providers/Auth/SentinelTest.php
tests/Providers/JWT/NamshiTest.php
tests/Providers/JWT/ProviderTest.php
tests/Providers/Storage/IlluminateTest.php
tests/Stubs/JWTProviderStub.php
tests/TokenTest.php
tests/Validators/PayloadValidatorTest.php
tests/Validators/TokenValidatorTest.php

Declare test cases properties

---

tests/Claims/ClaimTest.php
tests/JWTAuthTest.php
tests/ManagerTest.php
tests/Middleware/AuthenticateTest.php
tests/Middleware/RefreshTokenTest.php
tests/PayloadTest.php
tests/Providers/JWT/NamshiTest.php
tests/Validators/PayloadValidatorTest.php
tests/Validators/TokenValidatorTest.php

Use `@expectedException` notation

Use @expectedException notation

---

.php_cs
.styleci.yml

Add logical_not_operators_with_successor_space

Add logical_not_operators_with_successor_space

---

tests/JWTAuthTest.php

Use stricter assertion

---

tests/Claims/FactoryTest.php
tests/FactoryTest.php
tests/JWTAuthTest.php
tests/ManagerTest.php
tests/PayloadTest.php

Use ::class notation in tests

---

.scrutinizer.yml
.travis.yml

Scrutinizer-CI seems to have issue for test coverage even with an insanely long timeout.
https://codecov.io/ is free for public projects and its Chrome extension integrates with Github: https://chrome.google.com/webstore/detail/codecov-extension/keefkhehidemnokodkdkejapdgfjmijf

A test coverage that just works fine

---

tests/JWTAuthTest.php
tests/ManagerTest.php
tests/Providers/JWT/NamshiTest.php

Remove unused variables in tests

Remove unused variables in tests

---

src/Blacklist.php

No need to create a new instance

No need to create a new instance

---

src/Blacklist.php
src/Factory.php

No need to ->format('U') and cast in int
Use timestamp directly

Use timestamp

---

src/Blacklist.php
src/PayloadFactory.php
src/Validators/PayloadValidator.php
tests/JWTAuthTest.php
tests/JWTManagerTest.php
tests/Providers/JWT/NamshiAdapterTest.php

Just some updates that @lucasmichot pushed to develop that I wanted back on master while I was tinkering.

Cleaner Carbon expressions

---

src/Providers/LumenServiceProvider.php

Fix doblock

---

src/Providers/LumenServiceProvider.php

Stay consistant with constructor without arguments

Stay consistant with constructor without arguments

---

.php_cs

Sync with styleci

---

.php_cs
.styleci.yml

Make sure PR against master are also checked by StyleCI

---

src/Blacklist.php

No need to create a 3rd instance
Also rename `$refreshExp` to `$iat`

No need to create a 3rd instance

---

src/JWTGuard.php
src/Manager.php
src/Payload.php

Fix some throws docblockcs

---

tests/Providers/JWT/NamshiTest.php

Remove a useless variable in NamshiTest

Remove a useless variable in NamshiTest

---

src/JWTGuard.php

In the entire project, only this setter is not fluid.
I suppsose this was not on purpose

Make setter fluid

---

.gitattributes

These files have been removed from the project

Cleanup gitattributes

---

.travis.yml

`--dev` flag comes by default.

Remove useless default --dev flag

---

src/Token.php

Ensure the token value is a string

Ensure the token value is a string

---

src/Blacklist.php

Use FQN docblocks

---

src/Factory.php

WIP - Fix misordered imports

---

src/Providers/LaravelServiceProvider.php
src/Providers/LumenServiceProvider.php
tests/BlacklistTest.php
tests/FactoryTest.php
tests/ManagerTest.php
tests/PayloadTest.php
tests/Providers/Auth/OctoberTest.php
tests/Providers/Auth/SentinelTest.php

Misordered imports

---

.styleci.yml

Use the same styleci definition on master as the one used on develop

---

.travis.yml

* Use a matrix
* Only require without installing before

[WIP] Travis

---

tests/AbstractTestCase.php
tests/BlacklistTest.php
tests/Claims/ClaimTest.php
tests/Claims/FactoryTest.php
tests/FactoryTest.php
tests/Http/ParserTest.php
tests/JWTAuthTest.php
tests/JWTGuardTest.php
tests/ManagerTest.php
tests/Middleware/AuthenticateTest.php
tests/Middleware/CheckTest.php
tests/Middleware/RefreshTokenTest.php
tests/PayloadTest.php
tests/Providers/Auth/IlluminateTest.php
tests/Providers/Auth/OctoberTest.php
tests/Providers/Auth/SentinelTest.php
tests/Providers/JWT/NamshiTest.php
tests/Providers/JWT/ProviderTest.php
tests/Providers/Storage/IlluminateTest.php
tests/TokenTest.php
tests/Validators/PayloadValidatorTest.php
tests/Validators/TokenValidatorTest.php

Test should never rely on `time()` but on `\Carbon\Carbon::setTestNow()` instead

Fix all time issues in test

---

tests/Claims/ClaimTest.php
tests/ManagerTest.php

Use `$this->testNowTimestamp` when appropriate.

Use testNowTimestamp

---

tests/BlacklistTest.php
tests/FactoryTest.php
tests/Http/ParserTest.php
tests/JWTAuthTest.php
tests/JWTGuardTest.php
tests/ManagerTest.php
tests/Middleware/AuthenticateTest.php
tests/Middleware/CheckTest.php
tests/Middleware/RefreshTokenTest.php
tests/PayloadTest.php
tests/Providers/Auth/IlluminateTest.php
tests/Providers/Auth/OctoberTest.php
tests/Providers/Auth/SentinelTest.php
tests/Providers/JWT/NamshiTest.php
tests/Providers/Storage/IlluminateTest.php

Use imports

---

src/Claims/DatetimeTrait.php
src/Claims/Expiration.php
src/Claims/IssuedAt.php
src/Claims/NotBefore.php
tests/Claims/DatetimeClaimTest.php

Alternative for #521 with a trait.
**Note:**
This time we get rid of the original `validate` function description.
---
Solution for #510

Let time related claims handle DateTimeInterface values with a DatetimeTrait

---

composer.json

Sort require-dev entries

---

tests/Claims/FactoryTest.php
tests/FactoryTest.php
tests/JWTAuthTest.php
tests/ManagerTest.php
tests/PayloadTest.php

Other imports

---

tests/Middleware/RefreshTokenTest.php

Add an empty line

---

src/Claims/Claim.php

Let `\Tymon\JWTAuth\Claims\Claim` implements `\Illuminate\Contracts\Support\Jsonable`

Let Claim implements Jsonable

---

src/Middleware/Authenticate.php

Pass previous exception to `\Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException`

Pass previous exception to UnauthorizedHttpException

---

src/Providers/JWT/Namshi.php

Fix a typo

---

src/Providers/Storage/Illuminate.php

Remove useless else

---

src/JWTGuard.php

Fix `\Tymon\JWTAuth\JWTGuard::attempt docblock`

Fix \Tymon\JWTAuth\JWTGuard::attempt docblock

---

src/Payload.php

Directly call `\Illuminate\Support\Str::startsWith`

Directly call \Illuminate\Support\Str::startsWith

---

tests/PayloadTest.php

Keep consistant test names

---

src/Exceptions/JWTException.php

Let user pass `$code` and `$previous` arguments.

Let user pass $code and $previous arguments

---

tests/Middleware/AuthenticateTest.php
tests/Middleware/CheckTest.php
tests/Middleware/RefreshTokenTest.php

Use \Tymon\JWTAuth\Http\Parser

---

tests/AbstractTestCase.php

Remove useless `null` argeument for `\Carbon\Carbon::setTestNow`

Remove useless argument

---

src/Http/AuthHeaders.php
src/Http/LumenRouteParams.php
src/Http/RouteParams.php
src/JWTGuard.php

Avoid empty return;

---

src/Contracts/Providers/Storage.php
src/Factory.php
src/JWT.php

Fix docblock

---

.gitattributes

Do not export `CONTRIBUTING.md`

Do not export CONTRIBUTING.md

---

tests/Claims/DatetimeClaimTest.php
tests/FactoryTest.php
tests/JWTAuthTest.php
tests/JWTGuardTest.php
tests/ManagerTest.php
tests/Middleware/AuthenticateTest.php
tests/Middleware/CheckTest.php
tests/Middleware/RefreshTokenTest.php
tests/Providers/Auth/IlluminateTest.php
tests/Providers/Auth/OctoberTest.php
tests/Providers/Auth/SentinelTest.php
tests/Providers/Storage/IlluminateTest.php

Declare test variables and update types

Declare test variables and update types

---

src/Blacklist.php
src/Factory.php
src/JWTGuard.php
src/Payload.php
src/Providers/Auth/October.php
src/Providers/Storage/Illuminate.php

Use === null or !== null notation

Use === null or !== null notation

---

src/Blacklist.php
src/Support/Utils.php
src/Validators/PayloadValidator.php

Add `isPast` and `isFuture` helpers.

Add isPast and isFuture helpers

---

tests/Validators/TokenValidatorTest.php

Split invalid tokens tests

---

src/Manager.php

Remove useless docblocks spaces

Remove useless docblocks spaces

---

phpunit.xml.dist
src/Console/JWTGenerateSecretCommand.php
src/Providers/AbstractServiceProvider.php

Respect Laravel app architecture and move \Commands to \Console

Move \Commands to \Console

---

src/Providers/JWT/Namshi.php

Missing docblock param

---

.travis.yml

And speedup Travis builds
---
See https://github.com/composer/composer/issues/4884#issuecomment-195229989

Cache packages and use --prefer-dist

---

tests/PayloadTest.php

Use ::class notation

---

src/Providers/LumenServiceProvider.php

I'm unsure if this was intentionally left out but I thought I'd push it if it was not.

Provide default configuration for Lumen

---

src/JWT.php

Fix a docblock

---

src/Http/Parser/Parser.php
tests/Http/ParserTest.php

test setChain, not its alias

---

tests/Claims/FactoryTest.php

Test all common `\Tymon\JWTAuth\Claims\Factory` fields

Test all common \Tymon\JWTAuth\Claims\Factory fields

---

src/Http/Parser/AuthHeaders.php
tests/Http/ParserTest.php

Add tests for setHeaderPrefix and setHeaderName

Add tests for setHeaderPrefix and setHeaderName

---

tests/Http/ParserTest.php

Add tests for `\Tymon\JWTAuth\Http\Parser\RouteParams::setKey`

Add tests for \Tymon\JWTAuth\Http\Parser\RouteParams::setKey

---

tests/JWTGuardTest.php

Add tests for unsucessful onceUsingId and tokenById

Add tests for unsucessful onceUsingId and tokenById

---

tests/JWTGuardTest.php

Add tests for `\Tymon\JWTAuth\JWTGuard::getRequest`

Add tests for \Tymon\JWTAuth\JWTGuard::getRequest

---

src/Http/Parser/AuthHeaders.php

Only calculate default values when this is required

Only calculate default values when this is required

---

src/Providers/JWT/Namshi.php

Also pass parent Exception and parent Exception code

Also pass parent Exception and parent Exception code

---

tests/Http/ParserTest.php

Remove useless header set

---

.styleci.yml
src/Http/Middleware/BaseMiddleware.php
src/JWT.php
src/JWTGuard.php
src/Payload.php
src/Providers/AbstractServiceProvider.php

Add missing return void docblock

Add missing return void docblock

---

src/Blacklist.php
src/JWTGuard.php

Fix 2 docblocks spacings

---

tests/PayloadTest.php

Also test Countable interface

---

README.md

Add VersionEye dependencies status

Add VersionEye dependencies status

---

src/Claims/Claim.php
src/Payload.php
tests/Claims/ClaimTest.php

As we already have `\Tymon\JWTAuth\Claims\Claim::toArray`

Let the claim implements Arrayable

---

src/Claims/Claim.php
src/Payload.php
tests/Fixtures/Foo.php
tests/PayloadTest.php

Add matches function to Payload

---

.codecov.yml
.gitattributes

Mute codecov PR comments

---

src/JWTAuth.php

Fix for #791 issue in version `0.5.9`

JWTAuth requireToken hotfix

---

composer.json

Support Laravel 5.3

---

README.md

Add PHP-Eye badge

---

.travis.yml
composer.json

Also use 5.3 packages for require-dev

Tests for Laravel 5.3

---

.travis.yml

Add Laravel 5.3 specific tests
---
Missing commit
See https://github.com/tymondesigns/jwt-auth/pull/837

Add Laravel 5.3 specific tests

---

.travis.yml

Codecov : remove deprecated before_install section.

Codecov : remove deprecated before_install section.

---

config/config.php
src/Console/JWTGenerateSecretCommand.php
src/Factory.php
src/JWT.php
src/JWTGuard.php
src/Manager.php
src/Payload.php
src/Providers/LumenServiceProvider.php
src/Validators/PayloadValidator.php

- Make array vertical
- console signature
- sort traits, imports and interfaces

Some style fix.

---

src/Blacklist.php
tests/ManagerTest.php

- Add blacklist getters.
- Also cover the blacklist setters.

Add blacklist getters.

---

src/Providers/JWT/JWTProvider.php

Adds the ability to set a custom secret for every JWT Token.

Add set/get secret to provider

---

tests/Providers/JWT/NamshiTest.php

I found one test that don't have assert to test behavior expected

Adding assert for the test of Namshi class

---

composer.json
tests/Providers/JWT/NamshiTest.php

Covering the behavior when the algorithm configured is wrong

 Adding test to cover ReflectionException

---

composer.json

Sort packages.

---

composer.json

Fix PHPUnit.

---

src/Providers/AbstractServiceProvider.php
src/Providers/LaravelServiceProvider.php
src/Providers/LumenServiceProvider.php

Extract middleware aliases
And determine only once if `aliasMiddleware` function exists

Extract middleware aliases

---

.travis.yml

Also test PHP 7.1 with Travis.

Also test PHP 7.1 with Travis.

---

tests/BlacklistTest.php
tests/Http/ParserTest.php
tests/JWTAuthTest.php
tests/Middleware/AuthenticateAndRenewTest.php
tests/Middleware/RefreshTokenTest.php
tests/Providers/Storage/IlluminateTest.php
tests/Stubs/TaggedStorage.php
tests/Validators/PayloadValidatorTest.php

Some tests fixes.

---

src/JWT.php

Ensure the token can also be null.
---
And also add some comments.

Ensure the token can also be null.

---

tests/Middleware/AuthenticateAndRenewTest.php
tests/Middleware/AuthenticateTest.php
tests/Middleware/CheckTest.php
tests/Middleware/RefreshTokenTest.php

Add comments for empty closures.

Add comments for empty closures.

---

src/Console/JWTGenerateSecretCommand.php
src/JWTGuard.php
src/Support/Utils.php
src/Validators/PayloadValidator.php
src/Validators/TokenValidator.php

Some source and docblocks fix

---

src/Blacklist.php
src/Claims/Collection.php
src/Claims/Factory.php
src/Exceptions/InvalidClaimException.php
src/Exceptions/JWTException.php
src/Factory.php
src/Http/Middleware/AuthenticateAndRenew.php
src/Http/Middleware/BaseMiddleware.php
src/Http/Middleware/Check.php
src/Http/Middleware/RefreshToken.php
src/Http/Parser/Parser.php
src/JWTAuth.php
src/JWTGuard.php
src/Manager.php
src/Providers/Auth/Illuminate.php
src/Providers/Auth/Sentinel.php
src/Providers/JWT/Namshi.php
src/Providers/JWT/Provider.php
src/Providers/Storage/Illuminate.php
src/Support/RefreshFlow.php
src/Validators/PayloadValidator.php

Lots of small fix

---

.travis.yml

No need to suggest package in Travis builds

No need to suggest package in Travis builds

---

src/Http/Middleware/AuthenticateAndRenew.php
src/Http/Middleware/BaseMiddleware.php
src/Http/Middleware/RefreshToken.php

Factorize the middleware

---

tests/Claims/IssuedAtTest.php
tests/Claims/NotBeforeTest.php
tests/PayloadTest.php
tests/Providers/JWT/NamshiTest.php

Some test fixes.

---

tests/AbstractTestCase.php
tests/BlacklistTest.php
tests/FactoryTest.php
tests/JWTAuthTest.php
tests/ManagerTest.php
tests/Middleware/AbstractMiddlewareTest.php
tests/Middleware/AuthenticateAndRenewTest.php
tests/Middleware/AuthenticateTest.php
tests/Middleware/CheckTest.php
tests/Middleware/RefreshTokenTest.php
tests/PayloadTest.php
tests/Validators/PayloadValidatorTest.php
tests/Validators/TokenValidatorTest.php

Some more test fixes
And add AbstractMiddlewareTest

More tests fixes

---

.travis.yml

Only run codecov once per build.
For PHP7.1 with L5.4

Only run codecov once per build

---

tests/Claims/FactoryTest.php
tests/Http/ParserTest.php

More code coverage

---

.travis.yml
tests/Claims/DatetimeClaimTest.php

Simplify TravisCI (and fix bug for HHVM)

Simplify TravisCI.

---

src/Http/Parser/AuthHeaders.php
src/Payload.php

Less calls using regex.

---

src/Exceptions/JWTException.php
tests/Claims/ClaimTest.php
tests/Claims/IssuedAtTest.php
tests/Claims/NotBeforeTest.php
tests/JWTAuthTest.php
tests/JWTGuardTest.php
tests/ManagerTest.php
tests/PayloadTest.php
tests/Providers/JWT/NamshiTest.php
tests/Validators/PayloadValidatorTest.php

Test exception messages

---

tests/Providers/JWT/NamshiTest.php

Import exceptions.

---

src/Http/Middleware/BaseMiddleware.php

- Added correct error response on checkForToken method

Fix in BaseMiddleware.php

---

src/Http/Parser/Cookies.php
src/Http/Parser/InputSource.php
src/Http/Parser/KeyTrait.php
src/Http/Parser/QueryString.php
src/Http/Parser/RouteParams.php

Add a KeyTrait

---

src/Http/Middleware/BaseMiddleware.php
src/Http/Parser/KeyTrait.php
src/Manager.php

Fix some docblocks CS.

---

composer.json

Add support section.

---

src/Console/JWTGenerateSecretCommand.php

Refactor the command.

---

tests/PayloadTest.php

Remove useless import.

---

src/JWTGuard.php

Fix docblock and return type

---

composer.json

Enable Laravel 5.5 package auto-discovery:
---
See:
- https://medium.com/@taylorotwell/package-auto-discovery-in-laravel-5-5-ea9e3ab20518
- https://github.com/barryvdh/laravel-debugbar/pull/643

Enable Laravel 5.5 package auto-discovery.
